#bin/sh
echo "Conclusion ✓"
read -p ""
echo "Should I learn Kotlin ?  ✓"
read -p ""
echo "2nd Most Loved language after rust - Stackoverflow survey 2018 ✓"
read -p ""
echo "https://insights.stackoverflow.com/survey/2018/ ✓"
read -p ""
echo "Most loved kotlin features: Null Safety, Extension function Java interoperability, data classes, high order functions"
read -p ""
echo "https://pusher.com/state-of-kotlin"
read -p ""
echo "For the future, Either Kotlin absorbs Java or Java become Kotlin ==> Any case, it worth learning"
read -p ""
echo "It's your choice :-) "
read -p ""
echo "Thank you for your attention ! "
